# Generated by Django 4.2.2 on 2023-07-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img', upload_to='templates\\img'),
        ),
    ]
