# Generated by Django 4.2.2 on 2023-07-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_like_dislike_comment_dislikes_comment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
